version: "3.9"

services:
  app:
    image: houzz_img
    container_name: houzz_app
    build:
      context: .
    ports:
      - "3000:3000"
    volumes:
      - ./:/usr/src/app
    env_file: .env
    command: [bin/docker-entry, local]
